version: "3"
services:
  shiny-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kochbuch_shiny-server
    ports:
      - 3838:3838
    volumes:
      - ./src/:/srv/shiny-server/
      - ./logs:/var/log/shiny-server/
    tty: true
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: kochbuch_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
